### ISSUE TITLE
Implement more purpose oriented main landing page

### ISSUE THREAD

**Issue by anorsich** [paralect/nextjs-landing-starter#3]
I've been working on the design for the [Ship](https://github.com/paralect/ship) site. I think it would a great idea to copy the main page from there once it ready. I like current landing, but we could do it even better by adding: 
- some call to action to the top of the main page
- some feature blocks
- footer with links to the privacy policy and terms of service and copyrights

**Comment by dimeous** [comment]
I try update components, but now error
Bug report

npm build return an error:

Failed to compile.
Error: > Build failed because of webpack errors
at ...next_starter\node_modules\next\dist\build\index.js:15:918

but in development all is ok.
Describe the bug

A clear and concise description of what the bug is.
npm build return an error:

Failed to compile.

TypeError: value.split is not a function

    Build error occurred
    Error: > Build failed because of webpack errors
    at D:\work\react\bookmap\next_starter\node_modules\next\dist\build\index.js:15:918
    at async D:\work\react\bookmap\next_starter\node_modules\next\dist\build\tracer.js:1:525
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! nextjs-landing-starter@2.5.1 build: next build src/client
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the nextjs-landing-starter@2.5.1 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! e_logs\2020-12-26T06_17_02_256Z-debug.log

Process finished with exit code 1

git : https://github.com/dimeous/next_landing_starter
